# Torch & Numpy

In [1]:
import torch
import numpy as np

## 1. convert numpy to tensor or vise versa

In [2]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print('\nnumpy array\n', np_data, 
      '\n\ntorch tensor', torch_data, 
      '\ntensor to array\n', tensor2array)


numpy array
 [[0 1 2]
 [3 4 5]] 

torch tensor 
 0  1  2
 3  4  5
[torch.IntTensor of size 2x3]
 
tensor to array
 [[0 1 2]
 [3 4 5]]


## 2. abs

In [3]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
abs_numpy = np.abs(data)
abs_tensor = torch.abs(tensor)
print(abs_numpy, abs_tensor)


[1 2 1 2] 
 1
 2
 1
 2
[torch.FloatTensor of size 4]



# 3. sin, cos, sigmoid, exp, mean

- array그대로 넣을 경우 에러 발생 반드시 tensor로 변형해서 넣어주자

In [4]:
print(torch.sin(data))
print(torch.cos(data))
print(torch.sigmoid(data))
print(torch.exp(data))
print(torch.mean(data))

TypeError: torch.sin received an invalid combination of arguments - got (list), but expected (torch.FloatTensor source)

In [5]:
print(torch.sin(tensor))
print(torch.cos(tensor))
print(torch.sigmoid(tensor))
print(torch.exp(tensor))
print(torch.mean(tensor))


-0.8415
-0.9093
 0.8415
 0.9093
[torch.FloatTensor of size 4]


 0.5403
-0.4161
 0.5403
-0.4161
[torch.FloatTensor of size 4]


 0.2689
 0.1192
 0.7311
 0.8808
[torch.FloatTensor of size 4]


 0.3679
 0.1353
 2.7183
 7.3891
[torch.FloatTensor of size 4]

0.0


## 4. Matrix Multiplication

In [6]:
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)

In [7]:
print(np.matmul(data, data))
print(torch.matmul(tensor, tensor))

[[ 7 10]
 [15 22]]

  7  10
 15  22
[torch.FloatTensor of size 2x2]



In [8]:
tensor * tensor


  1   4
  9  16
[torch.FloatTensor of size 2x2]